apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: paq3uujxj-dotnet-basic
  janus-idp.io/tekton: paq3uujxj-dotnet-basic
  backstage.io/kubernetes-id: paq3uujxj-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: paq3uujxj-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
